title: Bas' Blog
email: bas@basbroek.nl
description: Writes things. Mostly code.
baseurl: ""
url: ""
twitter_username: basthomas
github_username: BasThomas

excerpt_separator: <!--more-->

markdown: kramdown
theme: minima
permalink: pretty
plugins: ['jekyll-feed']
exclude:
  - Gemfile
  - Gemfile.lock
