title: Bas' Blog
email: bas@basbroek.nl
description: ""
baseurl: ""
url: https://www.basbroek.nl

social-network-links:
  github: BasThomas
  mastodon: iosdev.space/@bas

excerpt_separator: <!--more-->

markdown: kramdown
theme: minima
permalink: pretty
plugins: ['jekyll-feed']
exclude:
  - Gemfile
  - Gemfile.lock
