title: Bas' Blog
email: bas@basbroek.nl
description: ""
baseurl: ""
url: https://www.basbroek.nl

github: BasThomas
mastodon:
- username: bas
  instance: iosdev.space

excerpt_separator: <!--more-->

markdown: kramdown
theme: minima
permalink: pretty
plugins: ['jekyll-feed']
exclude:
  - Gemfile
  - Gemfile.lock
