title: Bas' Blog
email: bas@basbroek.nl
description: Writes things. Mostly code.
baseurl: ""
url: ""
twitter_username: BasThomas
github_username:  BasThomas

markdown: kramdown
theme: minima
permalink: pretty
plugins: ['jekyll-feed']
exclude:
  - Gemfile
  - Gemfile.lock
